# Generated by Django 3.0.1 on 2020-06-05 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoptions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='submittion_date',
            new_name='submission_date',
        ),
        migrations.RenameField(
            model_name='pet',
            old_name='vacccinationn',
            new_name='vaccinations',
        ),
        migrations.AlterField(
            model_name='pet',
            name='species',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='vaccine',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
